sudo: required
language: java
jdk:
 - oraclejdk8
services:
  - docker
script: "mvn cobertura:cobertura"
after_success:
 - bash <(curl -s https://codecov.io/bash)
 - mvn clean
 - mvn package
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
    mvn docker:build;
    docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD;
    docker tag ominidi/ominidi-web ominidi/ominidi-web:latest;
    docker push ominidi/ominidi-web:latest;
   fi
notifications:
 irc: "chat.freenode.net#ominidi.org"