facebook:
  graph_access_token_uri: "https://graph.facebook.com/oauth/access_token"
  page:
    id: 221685698257476
    feed_url: "/feed"
  application:
    app_id: ${APP_ID}
    app_secret: ${APP_SECRET}